window.V3 = {
  links: {
    agenda: "https://calendar.app.google/dQYwxnSev9Y9VLbD8",
    email: "mailto:fmartins.nascimento@outlook.com",
    linkedin: "https://linkedin.com/in/filipoow",
    github: "https://github.com/filipoow",
    filka: "https://filkastudio.com.br",
  },
  tech: [
    { n: "Databricks", c: "#FF3621", t: "#fff", s: "databricks" },
    { n: "AWS", c: "#FF9900", t: "#14110F", s: "amazonwebservices" },
    { n: "Python", c: "#3776AB", t: "#fff", s: "python" },
    { n: "Airflow", c: "#017CEE", t: "#fff", s: "apacheairflow" },
    { n: "Spark", c: "#E25A1C", t: "#fff", s: "apachespark" },
    { n: "dbt", c: "#FF694B", t: "#fff", s: "dbt" },
    { n: "Snowflake", c: "#29B5E8", t: "#fff", s: "snowflake" },
    { n: "Power BI", c: "#F2C811", t: "#14110F", s: "powerbi" },
    { n: "PostgreSQL", c: "#4169E1", t: "#fff", s: "postgresql" },
    { n: "Oracle", c: "#C74634", t: "#fff", s: "oracle" },
    { n: "OpenAI", c: "#10A37F", t: "#fff", s: "openai" },
    { n: "Salesforce", c: "#00A1E0", t: "#fff", s: "salesforce" },
    { n: "LangChain", c: "#1C3C3C", t: "#fff", s: "langchain" },
    { n: "Git", c: "#F05032", t: "#fff", s: "git" },
  ],
  pt: {
    nav: { work: "Trabalho.", exp: "Experiência.", filka: "Filka.", contact: "Contato." },
    hero: {
      rotate: ["Analytics", "Dados", "IA", "Automação"],
      fixed: "Engineer.",
      sub: "Construo soluções de dados, machine learning e IA generativa para empresas que querem decisões melhores e mais rápidas.",
      cta1: "Vamos conversar",
      cta2: "Ver trabalho",
      notes: [
        "Hoje sou Analytics Engineer Sênior na **Omie** e cofundador do **Filka Studio**, em São Paulo.",
        "Trabalho com **Databricks**, **AWS** e **Python** todos os dias, do pipeline ao modelo em produção.",
        "Já entreguei automações que economizam mais de **500 horas por mês** para os times que atendo.",
        "Cofundei o **Filka Studio** em 2022, onde juntamos programação e design digital.",
      ],
    },
    skills: { title: "Sempre construindo.", title2: "Sempre aprendendo." },
    work: {
      heading: "Meu trabalho.",
      tabs: ["Cases.", "Filka.", "Terminal."],
      hint: "Cinco projetos recentes. Resultado primeiro, tecnologia depois.",
      cases: [
        {
          co: "Omie", yr: "2025",
          name: "Alocação inteligente de clientes para franquias",
          metric: "100%", label: "do roteamento agora é automatizado",
          desc: "Antes o time fazia o match manual. Construí um modelo que calcula um score por cliente e cruza com o perfil de cada franquia.",
          tags: ["Python", "Scikit-learn", "Databricks"],
          img: "https://images.unsplash.com/photo-1511068797325-6083f0f872b1?fm=jpg&q=80&w=1200&fit=crop",
          credit: "Photo by Kelsey Knight on Unsplash", creditHref: "https://unsplash.com/@kelsoknight",
          alt: "Mão apontando para um mapa com pinos marcando localizações",
          detail: {
            discovery: [
              "Mapeei como o time de operações decidia manualmente qual franquia atendia cada cliente novo — critérios informais, sem nada registrado.",
              "Levantei o histórico de alocações no Databricks pra achar os sinais que mais pesavam: localização, porte do cliente, capacidade da franquia.",
              "Entrevistei os analistas responsáveis pra validar as hipóteses antes de sair modelando.",
            ],
            steps: [
              "Consolidação dos dados de clientes e franquias em uma tabela única no Databricks.",
              "Engenharia de features: distância, capacidade ociosa, histórico de performance da franquia.",
              "Modelo de scoring em Scikit-learn, validado contra as alocações manuais históricas.",
              "Pipeline de scoring automático em produção, com fallback pra revisão manual em casos de baixa confiança.",
              "Acompanhamento pós-lançamento: taxa de aceitação da alocação e tempo de resposta.",
            ],
          },
        },
        {
          co: "Omie", yr: "2025",
          name: "Chatbot interno com LLMs",
          metric: "−400h", label: "por mês de busca em base de conhecimento",
          desc: "Agente que consulta políticas, processos e documentação técnica em linguagem natural. Acelerou o onboarding do time.",
          tags: ["LLMs", "RAG", "OpenAI"],
          img: "https://images.unsplash.com/photo-1647154933795-422ba6b3034e?fm=jpg&q=80&w=1200&fit=crop",
          credit: "Photo by Vardan Papikyan on Unsplash", creditHref: "https://unsplash.com/@varpap",
          alt: "Pessoa digitando em um notebook de perto",
          detail: {
            discovery: [
              "Mapeei onde o conhecimento da empresa realmente vivia: Confluence, Google Docs, planilhas e mensagens soltas no Slack.",
              "Entrevistei gente recém-contratada pra entender onde perdiam mais tempo procurando informação.",
              "A maior dor não era falta de documentação — era não saber onde procurar.",
            ],
            steps: [
              "Ingestão e chunking dos documentos internos: políticas, processos, docs técnicos.",
              "Indexação vetorial e pipeline de RAG pra recuperar o trecho certo antes de gerar a resposta.",
              "Integração com a API da OpenAI pra geração de respostas, sempre citando a fonte.",
              "Interface de chat interna, plugada no fluxo de trabalho do time.",
              "Loop de feedback (👍/👎) pra saber onde a resposta errava e retreinar o retrieval.",
            ],
          },
        },
        {
          co: "Jadlog", yr: "2023",
          name: "ETL de KPIs comerciais",
          metric: "12", label: "dashboards executivos em uma fonte de verdade",
          desc: "Desenhei a estrutura comercial em Oracle e os pipelines em Spark e Airflow, alimentando o Power BI da diretoria.",
          tags: ["PL/SQL", "Spark", "Airflow"],
          img: "https://images.unsplash.com/photo-1686061593213-98dad7c599b9?fm=jpg&q=80&w=1200&fit=crop",
          credit: "Photo by 1981 Digital on Unsplash", creditHref: "https://unsplash.com/@1981digital",
          alt: "Tela de computador exibindo um dashboard de dados",
          detail: {
            discovery: [
              "Levantei com a diretoria comercial quais decisões dependiam de números que vinham de planilhas divergentes.",
              "Mapeei as fontes: banco Oracle transacional, exports manuais e três sistemas que nunca batiam entre si.",
              "Priorizei os 12 KPIs que realmente moviam decisão, descartando dezenas de métricas de vaidade.",
            ],
            steps: [
              "Modelagem da estrutura comercial em Oracle e PL/SQL, como fonte única de verdade.",
              "Pipelines de ETL em Spark orquestrados por Airflow, com teste de qualidade em cada etapa.",
              "Camada de agregação pensada pro consumo direto no Power BI, sem lógica duplicada nos relatórios.",
              "Dashboards executivos publicados e validados com cada área antes do rollout.",
              "Documentação da linhagem de dados, pra qualquer decisão em cascata ser rastreável.",
            ],
          },
        },
        {
          co: "Jadlog", yr: "2023",
          name: "Automação da tabela de fretes",
          metric: "−60h", label: "por semana de trabalho manual",
          desc: "Scripts que formatam tabelas de frete para VTEX, Intelipost e Loja Integrada. Eliminou retrabalho recorrente.",
          tags: ["Python", "Pandas"],
          img: "https://images.unsplash.com/photo-1685483749753-0dab7e144794?fm=jpg&q=80&w=1200&fit=crop",
          credit: "Photo by Brayden Prato on Unsplash", creditHref: "https://unsplash.com/@pratophoto",
          alt: "Corredores de um galpão logístico com prateleiras cheias de caixas",
          detail: {
            discovery: [
              "Acompanhei o time comercial formatando manualmente a mesma tabela de frete em três formatos diferentes, toda semana.",
              "Levantei as regras (às vezes tácitas) de cada plataforma: colunas exigidas, unidades, faixas de peso e CEP.",
              "Encontrei inconsistências que geravam erro de cotação lá na frente, sem ninguém enxergar a causa raiz.",
            ],
            steps: [
              "Script em Python e Pandas pra ler a tabela mestre de frete e validar as regras de negócio antes de exportar.",
              "Três exportadores dedicados — VTEX, Intelipost, Loja Integrada — cada um respeitando o schema da plataforma.",
              "Validações automáticas de faixa de peso, CEP e valor, pra pegar erro antes de subir pro sistema.",
              "Rotina agendada, substituindo o processo manual semanal por um job único.",
              "Handoff documentado pro time comercial rodar sozinho, sem depender de mim a cada tabela nova.",
            ],
          },
        },
        {
          co: "Filka Studio", yr: "2024",
          name: "Salesforce sob medida",
          metric: "2", label: "clientes ativos com Sales Cloud customizado",
          desc: "Implementações de Sales Cloud, automações em Apex e Flows, integrações via API e dashboards executivos.",
          tags: ["Apex", "Flows", "LWC"],
          img: "https://images.unsplash.com/photo-1758518732175-5d608ba3abdf?fm=jpg&q=80&w=1200&fit=crop",
          credit: "Photo by Vitaly Gariev on Unsplash", creditHref: "https://unsplash.com/@silverkblack",
          alt: "Equipe reunida em volta de uma mesa em escritório moderno",
          detail: {
            discovery: [
              "Reunião de diagnóstico com cada cliente pra entender o funil de vendas real — não o que um CRM genérico assumia que era.",
              "Mapeamento dos sistemas que precisavam conversar com o Salesforce: ERP, WhatsApp, planilha de comissionamento.",
              "Levantamento dos relatórios que a diretoria realmente olhava, pra desenhar os dashboards certos desde o início.",
            ],
            steps: [
              "Modelagem de objetos e do funil de vendas customizado no Sales Cloud.",
              "Automações em Apex e Flows pra eliminar etapas manuais: roteamento de lead, alçadas de aprovação.",
              "Integrações via API com os sistemas do cliente, ERP e ferramentas de comunicação.",
              "Componentes customizados em LWC onde o Salesforce padrão não dava conta do fluxo do cliente.",
              "Dashboards executivos e handover documentado pro time do cliente manter sozinho.",
            ],
          },
        },
      ],
      filka: {
        kicker: "Estúdio, desde 2022",
        title: "Cofundei o Filka Studio para juntar dois mundos que costumam viver separados.",
        body: "Programação e design digital. Atendemos clientes que precisam dos dois, entregues juntos e bem feitos. Não vendemos pacote pronto: conversamos primeiro, entendemos o problema, e só depois propomos o caminho mais curto até o resultado.",
        items: [
          "Salesforce sob medida",
          "Automações em Python",
          "Sites e landing pages",
          "Identidade visual e marca",
          "Business Intelligence",
          "Consultoria e diagnóstico",
        ],
        cta: "Ver o site da Filka",
      },
      terminalHint: "Digite help para ver os comandos.",
      detailLabels: {
        view: "Ver case completo", back: "Trabalho",
        discovery: "O que eu levantei", steps: "Passo a passo",
        cta: "Vamos conversar sobre o seu projeto",
      },
    },
    stats: {
      heading: "Alguns números.",
      items: [
        { v: "+500h", l: "economizadas por mês", n: "Python", c: "#3776AB", t: "#fff", s: "python" },
        { v: "20+", l: "soluções em produção", n: "Databricks", c: "#FF3621", t: "#fff", s: "databricks" },
        { v: "5 anos", l: "trabalhando com dados", n: "AWS", c: "#FF9900", t: "#14110F", s: "amazonwebservices" },
        { v: "2", l: "clientes na Filka", n: "Salesforce", c: "#00A1E0", t: "#fff", s: "salesforce" },
      ],
    },
    exp: {
      accent: "Desconstruindo",
      rest: "minha experiência.",
      items: [
        {
          role: "Analytics Engineer Sênior", co: "Omie", period: "2026 até hoje",
          bullets: [
            "Desenvolvo projetos de **IA aplicada** e dados em **Databricks**",
            "Modelos de **Machine Learning** para alocação e scoring",
            "Agentes com **LLMs** e **RAG** sobre a base de conhecimento interna",
          ],
        },
        {
          role: "Analista de Dados Pleno", co: "Omie", period: "2024 a 2026",
          bullets: [
            "Novo desafio em **SaaS**, com foco em analytics de produto",
            "Comecei a explorar **ML** e **IA generativa** dentro da empresa",
          ],
        },
        {
          role: "Cofundador", co: "Filka Studio", period: "2022 até hoje",
          bullets: [
            "Estúdio de **programação e design digital**, fundado em São Paulo",
            "Soluções em **Salesforce**, automações e **Business Intelligence**",
            "Atendimento de clientes de ponta a ponta, do diagnóstico ao handover",
          ],
        },
        {
          role: "Analista de Dados Júnior a Pleno", co: "Jadlog", period: "2022 a 2024",
          bullets: [
            "Construí **ETLs** e a base de **KPIs comerciais** da operação",
            "Pipelines em **Spark** e **Airflow** alimentando **Power BI**",
            "Modelagem em **Oracle** e **PL/SQL** para a área comercial",
          ],
        },
        {
          role: "Aprendiz, Backoffice", co: "Jadlog", period: "2021 a 2022",
          bullets: [
            "Comecei automatizando planilhas por conta própria, com **Python**",
            "Foi ali que descobri que dados era o que eu queria fazer",
          ],
        },
      ],
    },
    quotes: {
      heading: "O que dizem sobre mim.",
      items: [
        {
          q: "Profissional ímpar. Comprometimento e profissionalismo incomparáveis. Toda demanda destinada a ele era entregue no prazo, com riqueza de detalhes e aperfeiçoamentos.",
          a: "Michele Lopes", r: "Coordenadora Comercial, minha gestora na Jadlog", img: "assets/michele.png", url: "https://www.linkedin.com/in/michele-lopes-586539148/",
        },
        {
          q: "Nenhum obstáculo é grande demais para ele no desenvolvimento. Sempre traz inovação e melhorias, visão de processos surpreendente, frequentemente entrega mais do que o esperado. Foi meu braço direito como dev e tech lead, impecavelmente confiável.",
          a: "Lorena Santos Andrade", r: "Product Owner, colega de equipe na Jadlog", img: "assets/lorena.png", url: "https://www.linkedin.com/in/lorena-santos-andrade",
        },
      ],
    },
    faq: {
      heading: "Perguntas frequentes.",
      items: [
        { q: "Você atende como CLT, PJ ou freela?", a: "Os três. Vaga CLT com escopo desafiador, PJ pela Filka Studio para projetos pontuais ou contínuos, e freela para sprints de duas a seis semanas." },
        { q: "Quanto custa um projeto?", a: "Depende do escopo. Faço uma reunião de diagnóstico gratuita e devolvo uma proposta com três opções: mínimo viável, recomendado e completo. Você escolhe o que cabe no orçamento." },
        { q: "Em quanto tempo você começa?", a: "Normalmente de uma a duas semanas depois do aceite. Em caso urgente consigo encaixar mais rápido, é só falar comigo." },
        { q: "Você trabalha sozinho ou com time?", a: "Projeto pequeno, sozinho. Projeto maior, monto squad pela Filka Studio com designer, front e back." },
        { q: "Atende fora do Brasil?", a: "Sim. Trabalho remoto e tenho experiência em comunicação assíncrona em inglês." },
      ],
    },
    cta: {
      heading: "Bora trocar uma ideia?",
      reply: "Respondo toda mensagem em até 24 horas.",
      sub: "Diagnóstico inicial gratuito. Em trinta minutos saio com o problema entendido e uma proposta na sua caixa em até três dias.",
      b1: "Agendar 30 minutos",
      b2: "Mandar um email",
    },
    footer: { tag: "Dados, software e decisão.", privacy: "Privacidade" },
  },
  en: {
    nav: { work: "Work.", exp: "Experience.", filka: "Filka.", contact: "Contact." },
    hero: {
      rotate: ["Analytics", "Data", "AI", "Automation"],
      fixed: "Engineer.",
      sub: "I build data, machine learning and generative AI solutions for companies that want better decisions, faster.",
      cta1: "Let's talk",
      cta2: "See work",
      notes: [
        "Today I'm a Senior Analytics Engineer at **Omie** and co-founder of **Filka Studio**, in São Paulo.",
        "I work with **Databricks**, **AWS** and **Python** every day, from pipeline to model in production.",
        "I have shipped automations that save over **500 hours a month** for the teams I serve.",
        "I co-founded **Filka Studio** in 2022, where we bring code and digital design together.",
      ],
    },
    skills: { title: "Always building.", title2: "Always learning." },
    work: {
      heading: "My work.",
      tabs: ["Cases.", "Filka.", "Terminal."],
      hint: "Five recent projects. Results first, technology second.",
      cases: [
        {
          co: "Omie", yr: "2025",
          name: "Smart client to franchise allocation",
          metric: "100%", label: "of routing is now automated",
          desc: "The team used to match clients manually. I built a model that scores each client and crosses it with every franchise profile.",
          tags: ["Python", "Scikit-learn", "Databricks"],
          img: "https://images.unsplash.com/photo-1511068797325-6083f0f872b1?fm=jpg&q=80&w=1200&fit=crop",
          credit: "Photo by Kelsey Knight on Unsplash", creditHref: "https://unsplash.com/@kelsoknight",
          alt: "A hand pointing at a map marked with location pins",
          detail: {
            discovery: [
              "Mapped how ops manually decided which franchise served each new client — informal criteria, nothing recorded.",
              "Dug through the allocation history in Databricks for the signals that mattered most: location, client size, franchise capacity.",
              "Interviewed the analysts doing the matching to validate hypotheses before modeling anything.",
            ],
            steps: [
              "Consolidated client and franchise data into a single table in Databricks.",
              "Feature engineering: distance, idle capacity, franchise performance history.",
              "Scoring model in Scikit-learn, validated against the historical manual allocations.",
              "Automated scoring pipeline in production, with a fallback to manual review for low-confidence cases.",
              "Post-launch tracking: allocation acceptance rate and response time.",
            ],
          },
        },
        {
          co: "Omie", yr: "2025",
          name: "Internal LLM chatbot",
          metric: "−400h", label: "per month searching the knowledge base",
          desc: "An agent that queries policies, processes and technical docs in natural language. Sped up onboarding across the team.",
          tags: ["LLMs", "RAG", "OpenAI"],
          img: "https://images.unsplash.com/photo-1647154933795-422ba6b3034e?fm=jpg&q=80&w=1200&fit=crop",
          credit: "Photo by Vardan Papikyan on Unsplash", creditHref: "https://unsplash.com/@varpap",
          alt: "Close-up of a person typing on a laptop",
          detail: {
            discovery: [
              "Mapped where company knowledge actually lived: Confluence, Google Docs, spreadsheets, loose Slack messages.",
              "Interviewed recent hires to find out where they lost the most time searching for information.",
              "The real pain wasn't missing documentation — it was not knowing where to look.",
            ],
            steps: [
              "Ingestion and chunking of internal docs: policies, processes, technical documentation.",
              "Vector indexing and a RAG pipeline to retrieve the right passage before generating an answer.",
              "Integration with the OpenAI API for answer generation, always citing the source.",
              "Internal chat interface, plugged straight into the team's workflow.",
              "Feedback loop (👍/👎) to spot wrong answers and retrain retrieval.",
            ],
          },
        },
        {
          co: "Jadlog", yr: "2023",
          name: "Commercial KPI ETL",
          metric: "12", label: "executive dashboards on one source of truth",
          desc: "Designed the commercial structure in Oracle and the Spark and Airflow pipelines feeding leadership's Power BI.",
          tags: ["PL/SQL", "Spark", "Airflow"],
          img: "https://images.unsplash.com/photo-1686061593213-98dad7c599b9?fm=jpg&q=80&w=1200&fit=crop",
          credit: "Photo by 1981 Digital on Unsplash", creditHref: "https://unsplash.com/@1981digital",
          alt: "Computer screen displaying a data dashboard",
          detail: {
            discovery: [
              "Worked with commercial leadership to find which decisions relied on numbers pulled from diverging spreadsheets.",
              "Mapped the sources: the transactional Oracle database, manual exports, and three systems that never agreed.",
              "Prioritized the 12 KPIs that actually drove decisions, cutting dozens of vanity metrics.",
            ],
            steps: [
              "Modeled the commercial structure in Oracle and PL/SQL as the single source of truth.",
              "ETL pipelines in Spark orchestrated by Airflow, with quality checks at every stage.",
              "An aggregation layer built for direct Power BI consumption, no duplicated logic across reports.",
              "Executive dashboards published and validated with each department before rollout.",
              "Documented data lineage so any downstream decision could be traced back.",
            ],
          },
        },
        {
          co: "Jadlog", yr: "2023",
          name: "Freight table automation",
          metric: "−60h", label: "per week of manual work",
          desc: "Scripts that format freight tables for VTEX, Intelipost and Loja Integrada. Killed recurring rework for good.",
          tags: ["Python", "Pandas"],
          img: "https://images.unsplash.com/photo-1685483749753-0dab7e144794?fm=jpg&q=80&w=1200&fit=crop",
          credit: "Photo by Brayden Prato on Unsplash", creditHref: "https://unsplash.com/@pratophoto",
          alt: "Aisles of a logistics warehouse with shelves full of boxes",
          detail: {
            discovery: [
              "Watched the commercial team manually reformat the same freight table into three different formats, every week.",
              "Mapped each platform's rules, some of them tacit: required columns, units, weight brackets, zip codes.",
              "Found inconsistencies that caused quoting errors further down the chain, with nobody seeing the root cause.",
            ],
            steps: [
              "Python and Pandas script to read the master freight table and validate business rules before any export.",
              "Three dedicated exporters — VTEX, Intelipost, Loja Integrada — each matching the platform's required schema.",
              "Automated checks on weight brackets, zip codes and values, to catch errors before upload.",
              "Scheduled job replacing the weekly manual process with a single run.",
              "Documented handoff so the commercial team could run it solo, without needing me for every new table.",
            ],
          },
        },
        {
          co: "Filka Studio", yr: "2024",
          name: "Tailored Salesforce",
          metric: "2", label: "active clients on customized Sales Cloud",
          desc: "Sales Cloud implementations, Apex and Flows automations, API integrations and executive dashboards.",
          tags: ["Apex", "Flows", "LWC"],
          img: "https://images.unsplash.com/photo-1758518732175-5d608ba3abdf?fm=jpg&q=80&w=1200&fit=crop",
          credit: "Photo by Vitaly Gariev on Unsplash", creditHref: "https://unsplash.com/@silverkblack",
          alt: "Team gathered around a table in a modern office",
          detail: {
            discovery: [
              "Discovery session with each client to map their actual sales funnel — not what a generic CRM assumed it was.",
              "Mapped which systems needed to talk to Salesforce: ERP, WhatsApp, the commission spreadsheet.",
              "Surveyed the reports leadership actually looked at, to design the right dashboards from day one.",
            ],
            steps: [
              "Object modeling and a customized sales funnel in Sales Cloud.",
              "Apex and Flows automations to remove manual steps: lead routing, approval thresholds.",
              "API integrations with the client's systems — ERP and communication tools.",
              "Custom LWC components wherever standard Salesforce couldn't handle the client's flow.",
              "Executive dashboards and a documented handover for the client's team to maintain solo.",
            ],
          },
        },
      ],
      filka: {
        kicker: "Studio, since 2022",
        title: "I co-founded Filka Studio to bring together two worlds that usually live apart.",
        body: "Code and digital design. We work with clients who need both, delivered together and done well. We don't sell off-the-shelf packages: we talk first, understand the problem, and only then propose the shortest path to results.",
        items: [
          "Tailored Salesforce",
          "Python automations",
          "Websites and landing pages",
          "Brand and visual identity",
          "Business Intelligence",
          "Consulting and discovery",
        ],
        cta: "Visit the Filka site",
      },
      terminalHint: "Type help to see the commands.",
      detailLabels: {
        view: "See full case", back: "Work",
        discovery: "What I found", steps: "Step by step",
        cta: "Let's talk about your project",
      },
    },
    stats: {
      heading: "A few numbers.",
      items: [
        { v: "+500h", l: "saved every month", n: "Python", c: "#3776AB", t: "#fff", s: "python" },
        { v: "20+", l: "solutions in production", n: "Databricks", c: "#FF3621", t: "#fff", s: "databricks" },
        { v: "5 years", l: "working with data", n: "AWS", c: "#FF9900", t: "#14110F", s: "amazonwebservices" },
        { v: "2", l: "clients at Filka", n: "Salesforce", c: "#00A1E0", t: "#fff", s: "salesforce" },
      ],
    },
    exp: {
      accent: "Destructuring",
      rest: "my work experience.",
      items: [
        {
          role: "Sr. Analytics Engineer", co: "Omie", period: "2026 to present",
          bullets: [
            "Building **applied AI** and data projects on **Databricks**",
            "**Machine Learning** models for allocation and scoring",
            "**LLM** and **RAG** agents over the internal knowledge base",
          ],
        },
        {
          role: "Mid Data Analyst", co: "Omie", period: "2024 to 2026",
          bullets: [
            "New challenge in **SaaS**, focused on product analytics",
            "Started exploring **ML** and **generative AI** inside the company",
          ],
        },
        {
          role: "Co-founder", co: "Filka Studio", period: "2022 to present",
          bullets: [
            "A **code and digital design** studio, founded in São Paulo",
            "**Salesforce** solutions, automations and **Business Intelligence**",
            "End to end client work, from discovery to handover",
          ],
        },
        {
          role: "Jr to Mid Data Analyst", co: "Jadlog", period: "2022 to 2024",
          bullets: [
            "Built the **ETLs** and the **commercial KPI** foundation",
            "**Spark** and **Airflow** pipelines feeding **Power BI**",
            "Modeling in **Oracle** and **PL/SQL** for the commercial team",
          ],
        },
        {
          role: "Apprentice, Back office", co: "Jadlog", period: "2021 to 2022",
          bullets: [
            "Started automating spreadsheets on my own, with **Python**",
            "That's where I found out data was what I wanted to do",
          ],
        },
      ],
    },
    quotes: {
      heading: "What people say about me.",
      items: [
        {
          q: "Outstanding professional. Unmatched commitment and professionalism. Every task assigned to him was delivered on time, with rich detail and refinement.",
          a: "Michele Lopes", r: "Commercial Coordinator, my manager at Jadlog", img: "assets/michele.png", url: "https://www.linkedin.com/in/michele-lopes-586539148/",
        },
        {
          q: "No obstacle is too big for him in development. Always brings innovation and improvements, a surprising eye for process, frequently delivers more than expected. He was my right hand as dev and tech lead, impeccably reliable.",
          a: "Lorena Santos Andrade", r: "Product Owner, teammate at Jadlog", img: "assets/lorena.png", url: "https://www.linkedin.com/in/lorena-santos-andrade",
        },
      ],
    },
    faq: {
      heading: "Frequently asked.",
      items: [
        { q: "Do you take full-time, contract or freelance?", a: "All three. Full-time with challenging scope, contract through Filka Studio for one-off or ongoing projects, and freelance for two to six week sprints." },
        { q: "How much does a project cost?", a: "It depends on scope. I run a free discovery call and send back a proposal with three tiers: minimum viable, recommended and full. You pick what fits the budget." },
        { q: "How fast can you start?", a: "Usually one to two weeks after sign-off. For urgent cases I can fit you in sooner, just tell me." },
        { q: "Do you work solo or with a team?", a: "Small projects, solo. Larger ones, I assemble a squad through Filka Studio with designer, frontend and backend." },
        { q: "Do you work outside Brazil?", a: "Yes. Fully remote, and comfortable with async communication in English." },
      ],
    },
    cta: {
      heading: "Want to chat?",
      reply: "I reply to every message within 24 hours.",
      sub: "Free initial diagnostic. In thirty minutes I walk away with the problem understood and a proposal in your inbox within three days.",
      b1: "Book 30 minutes",
      b2: "Send an email",
    },
    footer: { tag: "Data, software and decisions.", privacy: "Privacy" },
  },
};

window.V3.terminal = {
  pt: {
    boot: [
      "Portfolio OS v3.0 [Filipe Martins Edition]",
      "Carregando módulos ... ok",
      "Conectando ao Databricks ... ok",
      "Pronto.",
      "",
      'Digite "help" para ver os comandos disponíveis.',
    ],
    help: [
      "Comandos disponíveis:",
      "  whoami     quem eu sou",
      "  stack      tecnologias que eu uso",
      "  cases      projetos com resultado",
      "  exp        trajetória profissional",
      "  filka      sobre o meu estúdio",
      "  contact    como falar comigo",
      "  clear      limpa a tela",
    ],
    whoami: [
      "Filipe Martins",
      "Analytics Engineer Sênior na Omie, São Paulo, BR.",
      "Cofundador do Filka Studio desde 2022.",
      "Cinco anos transformando dados em decisão.",
    ],
    filka: [
      "Filka Studio, fundado em 2022.",
      "Programação e design digital no mesmo lugar.",
      "Salesforce, automações, sites, marca e BI.",
      "Site: filkastudio.com.br",
    ],
    contact: [
      "Email     fmartins.nascimento@outlook.com",
      "LinkedIn  linkedin.com/in/filipoow",
      "GitHub    github.com/filipoow",
      "Agenda    calendar.app.google/dQYwxnSev9Y9VLbD8",
    ],
    notFound: (c) => `comando não encontrado: ${c}. Digite "help".`,
  },
  en: {
    boot: [
      "Portfolio OS v3.0 [Filipe Martins Edition]",
      "Loading modules ... ok",
      "Connecting to Databricks ... ok",
      "Ready.",
      "",
      'Type "help" to see the available commands.',
    ],
    help: [
      "Available commands:",
      "  whoami     who I am",
      "  stack      the tech I work with",
      "  cases      projects with results",
      "  exp        career track",
      "  filka      about my studio",
      "  contact    how to reach me",
      "  clear      clears the screen",
    ],
    whoami: [
      "Filipe Martins",
      "Senior Analytics Engineer at Omie, São Paulo, BR.",
      "Co-founder of Filka Studio since 2022.",
      "Five years turning data into decisions.",
    ],
    filka: [
      "Filka Studio, founded in 2022.",
      "Code and digital design in the same place.",
      "Salesforce, automations, websites, brand and BI.",
      "Site: filkastudio.com.br",
    ],
    contact: [
      "Email     fmartins.nascimento@outlook.com",
      "LinkedIn  linkedin.com/in/filipoow",
      "GitHub    github.com/filipoow",
      "Calendar  calendar.app.google/dQYwxnSev9Y9VLbD8",
    ],
    notFound: (c) => `command not found: ${c}. Type "help".`,
  },
};

/* v4 hero copy — extends the shared V3 content */
window.V3.pt.h4 = {
  loc: "são paulo, brasil",
  lines: ["Eu transformo trabalho manual", "em sistemas que decidem sozinhos."],
  strip: ["5 anos entre dados e software", "500h/mês devolvidas aos times", "20+ soluções em produção"],
  cta1: "Ver trabalho",
  cta2: "Vamos conversar",
  side: "software · dados · ia generativa",
  barCta: "Vamos conversar",
  tiltHint: "toque para o crachá seguir o celular",
  axis: ["ATUALMENTE", "2021"],
  badge: { name: "Filipe Martins", role: "(Sr.) Analytics Engineer", pills: ["Omie", "Filka"] },
};
window.V3.en.h4 = {
  loc: "são paulo, brazil",
  lines: ["I turn manual work", "into systems that decide on their own."],
  strip: ["5 years across data and software", "500h/month given back to teams", "20+ solutions in production"],
  cta1: "See work",
  cta2: "Let's chat",
  side: "software · data · generative ai",
  barCta: "Let's talk",
  tiltHint: "tap to let the badge follow your phone",
  axis: ["PRESENT", "2021"],
  badge: { name: "Filipe Martins", role: "(Sr.) Analytics Engineer", pills: ["Omie", "Filka"] },
};
