// Conteúdo bilíngue centralizado
window.SITE_CONTENT = {
  pt: {
    nav: { work: "Trabalho", about: "Sobre", services: "Serviços", contact: "Contato" },
    hero: {
      eyebrow: "Analytics Engineer Sr · São Paulo, BR",
      title: "Eu construo sistemas de dados que pensam por você.",
      subtitle: "Pipelines em Databricks, modelos de ML em produção e agentes de IA generativa que poupam centenas de horas por mês — em empresas SaaS, logística e e-commerce.",
      cta1: "Agendar conversa",
      cta2: "Ver cases",
      availability: "Disponível para novos projetos e propostas",
    },
    proof: {
      label: "Hoje na",
      role: "Analytics Engineer Sr · Omie",
      since: "Desde 2024",
      filka: "Cofundador · Filka Studio",
      filkaSince: "Desde 2022",
    },
    intro: {
      title: "Resumo executivo",
      body: "Comecei no backoffice da Jadlog vendo planilhas de 80 mil linhas devorarem o dia da equipe. Em 3 anos virei Analista de Dados Pleno construindo a base de KPIs comerciais. Hoje, na Omie, lidero soluções de Machine Learning para alocação de franquias e chatbots com LLMs que destravam o conhecimento interno de centenas de pessoas. Em paralelo, na Filka Studio (que cofundei em 2022), entrego automações Salesforce e soluções de dados sob medida para clientes que precisam de velocidade sem perder qualidade.",
    },
    services: {
      title: "Como posso te ajudar",
      subtitle: "Três frentes onde meu trabalho gera retorno claro.",
      items: [
        {
          tag: "01",
          name: "Pipelines de dados modernos",
          desc: "Databricks, AWS, dbt, Airflow. Da ingestão ao consumo, com observabilidade e CI/CD desde o dia 1.",
          tags: ["Databricks", "AWS", "Airflow", "dbt"],
        },
        {
          tag: "02",
          name: "IA generativa aplicada",
          desc: "Chatbots internos, agentes que consultam a base de conhecimento da empresa, automação de fluxos cognitivos com LLMs.",
          tags: ["LLMs", "RAG", "OpenAI API", "Python"],
        },
        {
          tag: "03",
          name: "Machine Learning de negócio",
          desc: "Modelos de classificação, regressão e otimização para problemas reais — alocação, churn, scoring, previsão.",
          tags: ["Scikit-learn", "Feature Eng.", "MLOps"],
        },
        {
          tag: "04",
          name: "Salesforce + automação",
          desc: "Via Filka Studio: Apex, Flows, LWC, integrações via API e qualidade de dados em CRM.",
          tags: ["Apex", "Flows", "LWC", "APIs"],
        },
      ],
    },
    cases: {
      title: "Cases recentes",
      subtitle: "Resultado primeiro, tecnologia depois.",
      items: [
        {
          company: "Omie",
          year: "2025",
          name: "Alocação inteligente de clientes → franquias",
          metric: "100%",
          metricLabel: "do roteamento, antes manual, agora automatizado",
          desc: "Modelo de ML que substitui o processo manual do time. Calcula um score por cliente e cruza com o perfil de cada franquia, gerando o match ideal para o atendimento.",
          tags: ["Python", "Scikit-learn", "Databricks"],
        },
        {
          company: "Omie",
          year: "2025",
          name: "Chatbot interno com LLMs",
          metric: "−400h/mês",
          metricLabel: "tempo de busca em base de conhecimento",
          desc: "Agente RAG que consulta políticas, processos e documentação técnica. Reduziu tickets de dúvidas internas e acelerou onboarding.",
          tags: ["LLMs", "RAG", "OpenAI", "Python"],
        },
        {
          company: "Jadlog",
          year: "2023",
          name: "ETL de KPIs comerciais",
          metric: "12 dashboards",
          metricLabel: "consolidados em 1 fonte de verdade",
          desc: "Desenho da estrutura comercial em Oracle + pipelines em Spark/Airflow, alimentando Power BI executivo.",
          tags: ["PL/SQL", "Spark", "Airflow", "Power BI"],
        },
        {
          company: "Jadlog",
          year: "2023",
          name: "Automação de tabela de fretes",
          metric: "−60h/semana",
          metricLabel: "de trabalho manual",
          desc: "Scripts em Python que formatam tabelas para VTEX, Intelipost e Loja Integrada. Eliminou retrabalho recorrente.",
          tags: ["Python", "Pandas", "Xlsxwriter"],
        },
        {
          company: "Filka Studio",
          year: "2024",
          name: "Salesforce sob medida — Filka",
          metric: "2 clientes",
          metricLabel: "ativos com Sales Cloud customizado",
          desc: "Implementações Sales Cloud, automações em Apex/Flows, integrações via API e dashboards executivos para operações comerciais.",
          tags: ["Apex", "Flows", "LWC", "APIs"],
        },
      ],
    },
    stack: {
      title: "Stack atual",
      groups: [
        { name: "Plataformas de dados", items: ["Databricks", "AWS (S3, Lambda)", "Oracle", "Snowflake"] },
        { name: "Linguagens", items: ["Python", "SQL / PL-SQL", "Apex", "JavaScript"] },
        { name: "ML & IA", items: ["Scikit-learn", "OpenAI API", "RAG / LangChain", "Pandas"] },
        { name: "Engenharia", items: ["Airflow", "Spark", "dbt", "Git / CI-CD"] },
        { name: "Análise & BI", items: ["Power BI", "DAX", "Data Storytelling"] },
        { name: "Salesforce", items: ["Sales Cloud", "Lightning", "Flows", "LWC"] },
      ],
    },
    timeline: {
      title: "Trajetória",
      items: [
        { date: "2021", role: "Aprendiz · Backoffice", company: "Jadlog", note: "Comecei automatizando planilhas por conta própria." },
        { date: "2022", role: "Analista de Dados Jr → Pleno", company: "Jadlog", note: "Entrei pro time de dados. Construí ETLs e KPIs." },
        { date: "2022", role: "Cofundador", company: "Filka Studio", note: "Lançamos o estúdio focado em dados, automação e Salesforce." },
        { date: "2024", role: "Analista de Dados Pleno", company: "Omie", note: "Novo desafio em SaaS — comecei explorando ML e IA generativa." },
        { date: "2026", role: "Analytics Engineer Sr", company: "Omie", note: "Hoje. Desenvolvendo projetos de IA aplicada e dados em Databricks." },
      ],
    },
    testimonials: {
      title: "O que dizem",
      items: [
        {
          quote: "Profissional ímpar. Comprometimento e profissionalismo incomparável. Toda demanda destinada a ele era entregue no prazo, com riqueza de detalhes e aperfeiçoamentos.",
          author: "Michele Lopes",
          role: "Coordenadora Comercial · ex-gestora na Jadlog",
        },
        {
          quote: "Nenhum obstáculo é grande demais para ele no desenvolvimento, sempre trazendo inovações e melhorias. Visão de processos surpreendente, entrega frequentemente mais do que o esperado. Foi meu braço direito como dev e tech lead, impecavelmente confiável.",
          author: "Lorena Santos Andrade",
          role: "Product Owner · colega de equipe na Jadlog",
        },
      ],
    },
    faq: {
      title: "Como funciona contratar",
      items: [
        { q: "Você atende como CLT, PJ ou freela?", a: "Os três. Posição CLT com escopo desafiador, PJ via Filka Studio para projetos pontuais ou contínuos, e freela para sprints de 2 a 6 semanas." },
        { q: "Quanto custa um projeto?", a: "Depende do escopo. Faço uma reunião de diagnóstico gratuita e devolvo proposta com 3 opções (mínimo viável, recomendado, completo) em até 3 dias." },
        { q: "Trabalha sozinho ou com time?", a: "Para projetos pequenos, sozinho. Para projetos maiores, monto squad com a Filka Studio (designer, dev front, dev back)." },
        { q: "Em quanto tempo começa?", a: "Normalmente 1 a 2 semanas após o aceite. Em casos urgentes, consigo encaixar mais rápido." },
        { q: "Atende fora do Brasil?", a: "Sim. Trabalho remoto e tenho experiência em comunicação assíncrona em inglês." },
      ],
    },
    contact: {
      title: "Vamos conversar",
      subtitle: "Diagnóstico inicial gratuito. Em 30 minutos saio com o problema entendido e uma proposta na sua caixa em até 3 dias.",
      cta1: "Agendar 30min",
      cta2: "Mandar e-mail",
    },
    footer: {
      tagline: "Sistemas de dados que pensam por você.",
      rights: "© 2026 Filipe Martins · Todos os direitos reservados",
    },
  },
  en: {
    nav: { work: "Work", about: "About", services: "Services", contact: "Contact" },
    hero: {
      eyebrow: "Sr. Analytics Engineer · São Paulo, BR",
      title: "I build data systems that think for you.",
      subtitle: "Databricks pipelines, ML models in production and generative AI agents that save hundreds of hours per month — across SaaS, logistics and e-commerce.",
      cta1: "Book a call",
      cta2: "See case studies",
      availability: "Open to new projects and proposals",
    },
    proof: {
      label: "Currently at",
      role: "Sr. Analytics Engineer · Omie",
      since: "Since 2024",
      filka: "Co-founder · Filka Studio",
      filkaSince: "Since 2022",
    },
    intro: {
      title: "Executive summary",
      body: "I started in Jadlog's back office watching 80k-row spreadsheets eat the team's day. In 3 years I became a mid-level data analyst building the commercial KPI foundation. Today at Omie I lead Machine Learning solutions for franchise allocation and LLM chatbots that unlock internal knowledge for hundreds of people. In parallel, at Filka Studio (which I co-founded in 2022), I deliver Salesforce automations and tailor-made data solutions for clients who need speed without losing quality.",
    },
    services: {
      title: "How I can help",
      subtitle: "Three fronts where my work generates clear ROI.",
      items: [
        {
          tag: "01",
          name: "Modern data pipelines",
          desc: "Databricks, AWS, dbt, Airflow. From ingestion to consumption, with observability and CI/CD from day 1.",
          tags: ["Databricks", "AWS", "Airflow", "dbt"],
        },
        {
          tag: "02",
          name: "Applied generative AI",
          desc: "Internal chatbots, agents that query the company knowledge base, automation of cognitive flows with LLMs.",
          tags: ["LLMs", "RAG", "OpenAI API", "Python"],
        },
        {
          tag: "03",
          name: "Business Machine Learning",
          desc: "Classification, regression and optimization models for real problems — allocation, churn, scoring, forecasting.",
          tags: ["Scikit-learn", "Feature Eng.", "MLOps"],
        },
        {
          tag: "04",
          name: "Salesforce + automation",
          desc: "Via Filka Studio: Apex, Flows, LWC, API integrations and CRM data quality.",
          tags: ["Apex", "Flows", "LWC", "APIs"],
        },
      ],
    },
    cases: {
      title: "Recent cases",
      subtitle: "Results first, tech second.",
      items: [
        {
          company: "Omie",
          year: "2025",
          name: "Smart client → franchise allocation",
          metric: "100%",
          metricLabel: "of routing, previously manual, now automated",
          desc: "ML model that replaces the team's manual process. Calculates a per-client score and crosses it with each franchise profile to generate the ideal match.",
          tags: ["Python", "Scikit-learn", "Databricks"],
        },
        {
          company: "Omie",
          year: "2025",
          name: "Internal LLM chatbot",
          metric: "−400h/mo",
          metricLabel: "knowledge-base search time",
          desc: "RAG agent that queries policies, processes and technical docs. Reduced internal Q&A tickets and sped up onboarding.",
          tags: ["LLMs", "RAG", "OpenAI", "Python"],
        },
        {
          company: "Jadlog",
          year: "2023",
          name: "Commercial KPI ETL",
          metric: "12 dashboards",
          metricLabel: "consolidated into 1 source of truth",
          desc: "Designed the commercial Oracle structure + Spark/Airflow pipelines feeding executive Power BI.",
          tags: ["PL/SQL", "Spark", "Airflow", "Power BI"],
        },
        {
          company: "Jadlog",
          year: "2023",
          name: "Freight table automation",
          metric: "−60h/week",
          metricLabel: "of manual work",
          desc: "Python scripts formatting tables for VTEX, Intelipost and Loja Integrada. Killed recurring rework.",
          tags: ["Python", "Pandas", "Xlsxwriter"],
        },
        {
          company: "Filka Studio",
          year: "2024",
          name: "Tailored Salesforce — Filka",
          metric: "2 clients",
          metricLabel: "active with custom Sales Cloud",
          desc: "Sales Cloud implementations, Apex/Flows automations, API integrations and executive dashboards for commercial operations.",
          tags: ["Apex", "Flows", "LWC", "APIs"],
        },
      ],
    },
    stack: {
      title: "Current stack",
      groups: [
        { name: "Data platforms", items: ["Databricks", "AWS (S3, Lambda)", "Oracle", "Snowflake"] },
        { name: "Languages", items: ["Python", "SQL / PL-SQL", "Apex", "JavaScript"] },
        { name: "ML & AI", items: ["Scikit-learn", "OpenAI API", "RAG / LangChain", "Pandas"] },
        { name: "Engineering", items: ["Airflow", "Spark", "dbt", "Git / CI-CD"] },
        { name: "Analysis & BI", items: ["Power BI", "DAX", "Data Storytelling"] },
        { name: "Salesforce", items: ["Sales Cloud", "Lightning", "Flows", "LWC"] },
      ],
    },
    timeline: {
      title: "Trajectory",
      items: [
        { date: "2021", role: "Apprentice · Back office", company: "Jadlog", note: "Started automating spreadsheets on my own." },
        { date: "2022", role: "Jr → Mid Data Analyst", company: "Jadlog", note: "Joined the data team. Built ETLs and KPIs." },
        { date: "2022", role: "Co-founder", company: "Filka Studio", note: "Launched the studio focused on data, automation and Salesforce." },
        { date: "2024", role: "Mid Data Analyst", company: "Omie", note: "New SaaS challenge — started exploring ML and generative AI." },
        { date: "2026", role: "Sr. Analytics Engineer", company: "Omie", note: "Today. Building applied AI projects and data on Databricks." },
      ],
    },
    testimonials: {
      title: "What people say",
      items: [
        {
          quote: "Outstanding professional. Unmatched commitment and professionalism. Every task assigned was delivered on time, with rich detail and refinement.",
          author: "Michele Lopes",
          role: "Commercial Coordinator · ex-manager at Jadlog",
        },
        {
          quote: "No obstacle is too big in development — always brings innovation and improvements. Surprising process vision, frequently delivers more than expected. Was my right hand as dev and tech lead, impeccably reliable.",
          author: "Lorena Santos Andrade",
          role: "Product Owner · teammate at Jadlog",
        },
      ],
    },
    faq: {
      title: "How hiring works",
      items: [
        { q: "Do you take full-time, contract or freelance?", a: "All three. Full-time with challenging scope, contract via Filka Studio for one-off or ongoing projects, and freelance for 2–6 week sprints." },
        { q: "How much does a project cost?", a: "Depends on scope. I run a free 30-min discovery call and send back a proposal with 3 tiers (MVP, recommended, full) within 3 days." },
        { q: "Solo or with a team?", a: "Small projects: solo. Larger ones: I assemble a Filka Studio squad (designer, frontend, backend)." },
        { q: "How fast can we start?", a: "Usually 1–2 weeks after sign-off. Urgent cases I can fit in faster." },
        { q: "Do you work outside Brazil?", a: "Yes. Fully remote and comfortable with async English communication." },
      ],
    },
    contact: {
      title: "Let's talk",
      subtitle: "Free initial diagnostic. In 30 minutes I leave with the problem understood and a proposal in your inbox within 3 days.",
      cta1: "Book 30min",
      cta2: "Send email",
    },
    footer: {
      tagline: "Data systems that think for you.",
      rights: "© 2026 Filipe Martins · All rights reserved",
    },
  },
};

window.SITE_LINKS = {
  calendly: "https://calendly.com/emaildofilipe-m/30min",
  email: "mailto:fmartins.nascimento@outlook.com",
  linkedin: "https://linkedin.com/in/filipoow",
  github: "https://github.com/filipoow",
  filka: "https://www.behance.net/filkastudio",
};
